# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Bp')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Bp')
    _Bp = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Bp', [dirname(__file__)])
        except ImportError:
            import _Bp
            return _Bp
        try:
            _mod = imp.load_module('_Bp', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Bp = swig_import_helper()
    del swig_import_helper
else:
    import _Bp
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class Bp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Bp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Bp, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ni"] = _Bp.Bp_ni_set
    __swig_getmethods__["ni"] = _Bp.Bp_ni_get
    if _newclass:
        ni = _swig_property(_Bp.Bp_ni_get, _Bp.Bp_ni_set)
    __swig_setmethods__["nh"] = _Bp.Bp_nh_set
    __swig_getmethods__["nh"] = _Bp.Bp_nh_get
    if _newclass:
        nh = _swig_property(_Bp.Bp_nh_get, _Bp.Bp_nh_set)
    __swig_setmethods__["no"] = _Bp.Bp_no_set
    __swig_getmethods__["no"] = _Bp.Bp_no_get
    if _newclass:
        no = _swig_property(_Bp.Bp_no_get, _Bp.Bp_no_set)
    __swig_setmethods__["error_total"] = _Bp.Bp_error_total_set
    __swig_getmethods__["error_total"] = _Bp.Bp_error_total_get
    if _newclass:
        error_total = _swig_property(_Bp.Bp_error_total_get, _Bp.Bp_error_total_set)

    def __init__(self, ni, nh, no):
        this = _Bp.new_Bp(ni, nh, no)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def train(self, inputs, targets):
        return _Bp.Bp_train(self, inputs, targets)

    def print_weights(self):
        return _Bp.Bp_print_weights(self)

    def test_result(self, inputs):
        return _Bp.Bp_test_result(self, inputs)
    __swig_destroy__ = _Bp.delete_Bp
    __del__ = lambda self: None
Bp_swigregister = _Bp.Bp_swigregister
Bp_swigregister(Bp)


def make_matrix(row, column, min=0.0, max=0.0):
    return _Bp.make_matrix(row, column, min, max)
make_matrix = _Bp.make_matrix

def sigmoid(x):
    return _Bp.sigmoid(x)
sigmoid = _Bp.sigmoid

def dsigmoid(y):
    return _Bp.dsigmoid(y)
dsigmoid = _Bp.dsigmoid
# This file is compatible with both classic and new-style classes.


